// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SelfServiceCheckout.Data;

#nullable disable

namespace SelfServiceCheckout.Migrations
{
    [DbContext(typeof(SelfServiceCheckoutSQLiteDbContext))]
    partial class SelfServiceCheckoutSQLiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("SelfServiceCheckout.Models.MoneyDenomination", b =>
                {
                    b.Property<int>("Currency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Denomination")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Currency", "Denomination");

                    b.ToTable("MoneyDenominations");
                });
#pragma warning restore 612, 618
        }
    }
}
